{
    "beach_0.jpg": {
        "main_subject": "un parasol beige au-dessus de deux transats en bois",
        "background": "eau turquoise peu profonde, petits îlots rocheux, sable blanc",
        "detected_objects": [
            {
                "label": "parasol",
                "color": "beige/crème",
                "position": "centre",
                "state": "ouvert",
                "bounding_box": None,
            },
            {
                "label": "transats",
                "color": "bois clair",
                "position": "sous le parasol",
                "state": "coussins posés dessus",
                "bounding_box": None,
            },
            {
                "label": "table d'appoint",
                "color": "blanc",
                "position": "entre les transats",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "beach_1.jpg": {
        "main_subject": "un parasol multicolore entouré de chaises de plage",
        "background": "sable blanc, maisons de plage vertes et blanches au loin, dunes avec végétation",
        "detected_objects": [
            {
                "label": "parasol",
                "color": "multicolore (arc-en-ciel)",
                "position": "centre",
                "state": "ouvert",
                "bounding_box": None,
            },
            {
                "label": "chaises pliantes",
                "color": "bleu marine à motifs blancs",
                "position": "sous le parasol",
                "state": "vides",
                "bounding_box": None,
            },
            {
                "label": "bouée gonflable",
                "color": "vert fluo",
                "position": "à droite",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "sac de plage",
                "color": "vert foncé",
                "position": "à droite, au sol",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "beach_2.jpg": {
        "main_subject": "un parasol en paille avec une table et des chaises sur la plage",
        "background": "mer turquoise, colline en arrière-plan, ciel nuageux, sable blanc",
        "detected_objects": [
            {
                "label": "parasol en paille",
                "color": "beige/marron",
                "position": "centre, au-dessus de la table",
                "state": "à deux niveaux",
                "bounding_box": None,
            },
            {
                "label": "table ronde",
                "color": "gris/bois",
                "position": "centre",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "chaises",
                "color": "gris/bois",
                "position": "autour de la table",
                "state": "vides",
                "bounding_box": None,
            },
            {
                "label": "gobelet",
                "color": "blanc",
                "position": "sur la table",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "bench_0.jpg": {
        "main_subject": "un banc en bois usé avec pieds métalliques",
        "background": "pelouse et feuilles mortes éparses, léger chemin pavé visible à droite",
        "detected_objects": [
            {
                "label": "planches de bois",
                "color": "brun grisâtre, taché de mousse claire",
                "position": "centre",
                "state": "usées, fissurées",
                "bounding_box": None,
            },
            {
                "label": "pieds métalliques",
                "color": "gris/argenté",
                "position": "sous l'assise",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "feuilles mortes éparses",
                "color": "orange clair",
                "position": "posées sur l'assise",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "bench_1.jpg": {
        "main_subject": "un banc en bois isolé dans une forêt d'automne",
        "background": "sous-bois dense, feuillage jaune/orangé, troncs d'arbres sombres",
        "detected_objects": [
            {
                "label": "banc en bois",
                "color": "brun foncé",
                "position": "centre bas, en retrait",
                "state": "vide",
                "bounding_box": None,
            },
            {
                "label": "arbres",
                "color": "orange/jaune",
                "position": "arrière-plan, occupe la majorité du cadre",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "bench_2.jpg": {
        "main_subject": "un banc public recouvert de feuilles mortes",
        "background": "sol entièrement jonché de feuilles mortes brunes et orangées, vue de dessus",
        "detected_objects": [
            {
                "label": "dossier grillagé",
                "color": "noir/vert foncé",
                "position": "centre gauche",
                "state": "incliné, recourbé",
                "bounding_box": None,
            },
            {
                "label": "pied en béton",
                "color": "gris granuleux",
                "position": "premier plan gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "tas de feuilles mortes",
                "color": "marron/orange",
                "position": "centre, sur l'assise",
                "state": "amoncelées",
                "bounding_box": None,
            },
        ],
    },
    "bicycle_0.jpg": {
        "main_subject": "un vélo noir appuyé contre un mur rose/saumon",
        "background": "façade en stuc rose pâle, fenêtre à barreaux noirs, sol en briques mouillées",
        "detected_objects": [
            {
                "label": "pot en terre cuite",
                "color": "orange/terracotta",
                "position": "à droite du vélo",
                "state": "plante fanée",
                "bounding_box": None,
            },
            {
                "label": "fenêtre à barreaux",
                "color": "noir",
                "position": "centre droit",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "tuyau de descente",
                "color": "blanc",
                "position": "à gauche, le long du mur",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "bicycle_1.jpg": {
        "main_subject": "un vélo vintage bleu appuyé contre un mur décrépi",
        "background": "mur blanchi à la chaux, écaillé, tache de rouille visible, rue pavée",
        "detected_objects": [
            {
                "label": "panneau sens interdit",
                "color": "rouge et blanc",
                "position": "en haut à gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "voiture",
                "color": "gris/argenté",
                "position": "arrière-plan gauche",
                "state": "garée",
                "bounding_box": None,
            },
            {
                "label": "panier arrière",
                "color": "noir",
                "position": "Derrière la selle du vélo",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "plante",
                "color": "vert",
                "position": "au pied du vélo, en bas à gauche",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "bicycle_2.jpg": {
        "main_subject": "un vélo noir garé contre un mur en pierre, sous un réverbère",
        "background": "mur en pierre taillée, grille en fer forgé au sommet, arbres nus en arrière-plan",
        "detected_objects": [
            {
                "label": "réverbère",
                "color": "noir/vert foncé",
                "position": "centre, au-dessus du vélo",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "panneau de stationnement interdit",
                "color": "rouge et bleu",
                "position": "sur le réverbère, en hauteur",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "sac",
                "color": "orange",
                "position": "sur le porte-bagage arrière du vélo",
                "state": "attaché",
                "bounding_box": None,
            },
        ],
    },
    "car_0.jpg": {
        "main_subject": "une Fiat 500 noire vintage garée devant un garage automobile",
        "background": "rideaux métalliques verts, enseignes de garage 'ELETTRAUTO', mur beige couvert d'affiches",
        "detected_objects": [
            {
                "label": "scooter",
                "color": "noir",
                "position": "arrière-plan gauche",
                "state": "garé",
            },
            {
                "label": "enseigne de magasin",
                "color": "blanc, texte noir/bleu",
                "position": "en haut à gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "plaque d'immatriculation",
                "color": "blanc",
                "position": "avant de la voiture, en bas",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "rétroviseur",
                "color": "blanc/crème",
                "position": "côté conducteur",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "car_1.jpg": {
        "main_subject": "une berline grise garée le long d'un trottoir",
        "background": "mur beige taché d'humidité, passage piéton au sol, ombre d'arbre projetée",
        "detected_objects": [
            {
                "label": "panneau directionnel obligatoire",
                "color": "bleu et blanc",
                "position": "au-dessus de la voiture, sur le mur",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "fenêtre",
                "color": "cadre blanc",
                "position": "en haut à droite",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "passage piéton",
                "color": "blanc",
                "position": "premier plan",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "car_2.jpg": {
        "main_subject": "une voiture de sport rouge garée devant un bâtiment industriel abandonné",
        "background": "façade en briques beige tagguée de graffitis, auvents rouillés, plaques de neige au sol",
        "detected_objects": [
            {
                "label": "voiture de sport",
                "color": "rouge vif",
                "position": "centre",
                "state": "garée, jantes noires",
                "bounding_box": None,
            },
            {
                "label": "graffitis",
                "color": "multicolore (blanc, orange, noir)",
                "position": "sur le mur, derrière la voiture",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "porte de garage",
                "color": "gris/beige",
                "position": "gauche et droite du cadre",
                "state": "fermée, endommagée",
                "bounding_box": None,
            },
        ],
    },
    "desktop_0.jpg": {
        "main_subject": "une photo de dessus d'un bureau avec ordinateur portable et appareil photo",
        "background": "surface de bureau blanche unie",
        "detected_objects": [
            {
                "label": "appareil photo vintage",
                "color": "noir",
                "position": "gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "ordinateur portable",
                "color": "noir",
                "position": "centre",
                "state": "ouvert, écran éteint",
                "bounding_box": None,
            },
            {
                "label": "plante en pot",
                "color": "vert, pot rose",
                "position": "droite",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "lunettes",
                "color": "noir",
                "position": "en bas au centre",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "desktop_1.jpg": {
        "main_subject": "un bureau en bois avec un vase et un ordinateur portable ouvert",
        "background": "grand mur blanc uni, majoritairement vide",
        "detected_objects": [
            {
                "label": "vase en verre",
                "color": "vert",
                "position": "centre",
                "state": "contient une branche sèche",
                "bounding_box": None,
            },
            {
                "label": "clipboard",
                "color": "noir, papier blanc",
                "position": "droite",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "ordinateur portable",
                "color": "gris/argenté",
                "position": "gauche",
                "state": "ouvert, écran allumé",
                "bounding_box": None,
            },
            {
                "label": "lampe sur pied",
                "color": "blanc",
                "position": "extrême gauche",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "desktop_2.jpg": {
        "main_subject": "un bureau avec un ordinateur portable et une plante grimpante",
        "background": "mur beige clair, bureau en bois foncé",
        "detected_objects": [
            {
                "label": "plante grimpante",
                "color": "vert et blanc panaché",
                "position": "gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "livres",
                "color": "multicolore",
                "position": "arrière-plan droit",
                "state": "rangés debout",
                "bounding_box": None,
            },
            {
                "label": "bocal en verre avec couvercle",
                "color": "transparent",
                "position": "centre",
                "state": "fermé",
                "bounding_box": None,
            },
            {
                "label": "bouteille en verre",
                "color": "transparent, étiquette",
                "position": "gauche",
                "state": "contient une tige de plante",
                "bounding_box": None,
            },
        ],
    },
    "kitchen_0.jpg": {
        "main_subject": "un plan de travail avec un ananas et une bouilloire électrique",
        "background": "crédence carrelée blanche, placard en bois au-dessus",
        "detected_objects": [
            {
                "label": "ananas",
                "color": "jaune/vert",
                "position": "gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "bouilloire électrique",
                "color": "noir/argenté",
                "position": "centre gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "bouteille de jus d'orange",
                "color": "orange",
                "position": "droite",
                "state": "pleine",
                "bounding_box": None,
            },
            {
                "label": "bol de fraises",
                "color": "rouge",
                "position": "en bas à droite",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "Ustensiles",
                "color": "bois / noir",
                "position": "A gauche, derrière ananas",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "kitchen_1.jpg": {
        "main_subject": "un îlot de cuisine dressé avec de la vaisselle et de la nourriture",
        "background": "évier blanc, crédence carrelée blanche, ustensiles suspendus, posée sur le plan de travail : pot de plante blanc avec plante dedans, bocalen verre avec pomme à l'intérieur",
        "detected_objects": [
            {
                "label": "saladier en bois",
                "color": "bois clair",
                "position": "premier plan gauche",
                "state": "rempli de salade et légumes",
                "bounding_box": None,
            },
            {
                "label": "mug",
                "color": "bleu pastel",
                "position": "centre",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "assiette de gaufres",
                "color": "blanc",
                "position": "droite",
                "state": "garnie de myrtilles",
                "bounding_box": None,
            },
            {
                "label": "petit bol de myrtilles",
                "color": "blanc",
                "position": "centre bas",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "kitchen_2.jpg": {
        "main_subject": "un plan de travail avec un bol vide et des fruits coupés",
        "background": "crédence en bois clair, plan de travail gris foncé",
        "detected_objects": [
            {
                "label": "bol décoratif",
                "color": "gris/blanc à motifs",
                "position": "centre gauche",
                "state": "vide",
                "bounding_box": None,
            },
            {
                "label": "bol de fraises",
                "color": "rouge",
                "position": "arrière-plan droit",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "pommes vertes",
                "color": "vert",
                "position": "centre droit",
                "state": "une coupée en deux, une entière",
                "bounding_box": None,
            },
            {
                "label": "kiwi",
                "color": "vert/marron",
                "position": "centre",
                "state": "coupé en deux",
                "bounding_box": None,
            },
        ],
    },
    "livingroom_0.jpg": {
        "main_subject": "un salon moderne minimaliste avec un canapé d'angle beige",
        "background": "mur blanc, fenêtre avec rideaux beiges, parquet clair (rendu 3D probable, pas une photo réelle)",
        "detected_objects": [
            {
                "label": "canapé d'angle",
                "color": "beige",
                "position": "centre",
                "state": "coussins assortis",
                "bounding_box": None,
            },
            {
                "label": "tableau abstrait",
                "color": "tons beige/marron",
                "position": "au-dessus du canapé",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "suspensions rondes",
                "color": "blanc",
                "position": "plafond, centre",
                "state": "en grappe de 4 sphères",
                "bounding_box": None,
            },
            {
                "label": "tables basses gigognes",
                "color": "bois clair",
                "position": "premier plan centre",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "livingroom_1.jpg": {
        "main_subject": "un salon cosy avec un canapé gris et une table basse en bois",
        "background": "mur blanc à lambris, étagère avec cadres et plantes, parquet foncé",
        "detected_objects": [
            {
                "label": "canapé",
                "color": "gris clair",
                "position": "centre gauche",
                "state": "coussins et plaid",
                "bounding_box": None,
            },
            {
                "label": "table basse",
                "color": "bois clair",
                "position": "centre",
                "state": "livres empilés dessous",
                "bounding_box": None,
            },
            {
                "label": "pouf",
                "color": "motif ethnique multicolore",
                "position": "droite",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "réfrigérateur",
                "color": "vert pâle",
                "position": "arrière-plan gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "meuble livres",
                "color": "blanc",
                "position": "arrière-plan droite",
                "state": "Remplis de livre",
                "bounding_box": None,
            },
        ],
    },
    "livingroom_2.jpg": {
        "main_subject": "un salon loft avec un canapé d'angle gris foncé",
        "background": "grandes fenêtres ouvertes, sol carrelé à motifs et parquet, mur blanc avec bibliothèque",
        "detected_objects": [
            {
                "label": "canapé d'angle",
                "color": "gris foncé",
                "position": "centre",
                "state": "coussins et plaid empilés",
                "bounding_box": None,
            },
            {
                "label": "plante",
                "color": "vert, grand pot blanc",
                "position": "gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "bibliothèque",
                "color": "blanc, livres multicolores",
                "position": "droite",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "miroir sur pied",
                "color": "cadre noir",
                "position": "arrière-plan centre",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "table de cuisine avec chaise",
                "color": "noir / bois",
                "position": "Droite",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "market_0.jpg": {
        "main_subject": "un vendeur derrière un étal de fruits couvert",
        "background": "vêtements suspendus multicolores, lampes rouges suspendues, panneaux de prix en chinois",
        "detected_objects": [
            {
                "label": "vendeur",
                "color": "casquette grise, haut noir",
                "position": "centre, derrière l'étal",
                "state": "au téléphone",
                "bounding_box": None,
            },
            {
                "label": "pastèques",
                "color": "vert rayé",
                "position": "centre droit",
                "state": "empilées",
                "bounding_box": None,
            },
            {
                "label": "ananas",
                "color": "jaune/doré",
                "position": "centre gauche",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "fruit du dragon",
                "color": "rose/rouge",
                "position": "en bas à droite",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "market_1.jpg": {
        "main_subject": "un étal de marché de rue avec auvent vert",
        "background": "immeubles européens colorés à l'arrière-plan, rue pavée",
        "detected_objects": [
            {
                "label": "auvent",
                "color": "vert",
                "position": "au-dessus de l'étal",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "caissettes de fraises",
                "color": "rouge",
                "position": "centre, sur la table",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "pancartes de prix",
                "color": "blanc avec écriture noire",
                "position": "plantées dans les caissettes",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "passants",
                "color": "vêtements sombres",
                "position": "arrière-plan gauche",
                "state": "en mouvement",
                "bounding_box": None,
            },
        ],
    },
    "market_2.jpg": {
        "main_subject": "un étal de marché extérieur sous un parasol vert",
        "background": "arbres et végétation dense, structure en bois de l'étal",
        "detected_objects": [
            {
                "label": "parasol",
                "color": "vert clair",
                "position": "en haut à gauche",
                "state": "ouvert",
                "bounding_box": None,
            },
            {
                "label": "cageots de fruits",
                "color": "noir (bois foncé)",
                "position": "premier plan, en bas",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "tomates cerises suspendues",
                "color": "rouge",
                "position": "centre, en grappes suspendues",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "bouteilles de jus",
                "color": "orange/ambré",
                "position": "à droite",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "terace_0.jpg": {
        "main_subject": "un carrefour de rue parisienne avec un immeuble en pierre",
        "background": "rue pavée, immeubles en pierre de taille avec volets, ciel gris",
        "detected_objects": [
            {
                "label": "vélo",
                "color": "gris/noir",
                "position": "gauche, sur le trottoir",
                "state": "garé",
                "bounding_box": None,
            },
            {
                "label": "échoppe/boutique",
                "color": "rouge",
                "position": "droite",
                "state": "fermée, avec ardoise de menu",
                "bounding_box": None,
            },
            {
                "label": "bornes/potelets",
                "color": "noir",
                "position": "alignés au premier plan",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "passant",
                "color": "vêtements sombres",
                "position": "arrière-plan gauche",
                "state": "en marche",
                "bounding_box": None,
            },
        ],
    },
    "terace_1.jpg": {
        "main_subject": "une petite table de bistrot entre un vélo et des chaises pliantes",
        "background": "mur en plâtre écaillé, taché de rouille, sol pavé",
        "detected_objects": [
            {
                "label": "vélo",
                "color": "violet et blanc",
                "position": "gauche",
                "state": "appuyé contre le mur, avec panier",
                "bounding_box": None,
            },
            {
                "label": "table de bistrot",
                "color": "noir, plateau bois",
                "position": "centre",
                "state": "pliante",
                "bounding_box": None,
            },
            {
                "label": "objet rond",
                "color": "rouge",
                "position": "sur la table",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "chaise pliante en bois",
                "color": "bois naturel",
                "position": "droite",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "terace_2.jpg": {
        "main_subject": "une terrasse de restaurant vide de nuit avec un scooter garé",
        "background": "façade de restaurant éclairée en orange, palmiers de chaque côté",
        "detected_objects": [
            {
                "label": "scooter/mobylette",
                "color": "beige/crème",
                "position": "centre, premier plan",
                "state": "garé sur béquille",
                "bounding_box": None,
            },
            {
                "label": "chaises",
                "color": "jaune, coussins orange",
                "position": "autour des tables",
                "state": "vides",
                "bounding_box": None,
            },
            {
                "label": "lampe à tête de cheval",
                "color": "blanc (abat-jour), marron (cheval)",
                "position": "arrière-plan, visible à travers la vitre",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "portail en fer forgé",
                "color": "blanc/crème",
                "position": "droite",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "workbench_0.jpg": {
        "main_subject": "un établi de menuisier avec un rabot et un maillet en bois",
        "background": "étagères en bois avec bocaux, meuble à tiroirs en bois à droite",
        "detected_objects": [
            {
                "label": "rabot",
                "color": "noir et doré",
                "position": "centre",
                "state": "posé sur le côté",
                "bounding_box": None,
            },
            {
                "label": "maillet en bois",
                "color": "bois foncé",
                "position": "gauche du rabot",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "serre-joints",
                "color": "bleu/noir",
                "position": "en bas à droite, rangés",
                "state": "alignés sur étagère",
                "bounding_box": None,
            },
            {
                "label": "bocal en verre",
                "color": "transparent",
                "position": "arrière-plan gauche",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
    "workbench_1.jpg": {
        "main_subject": "un panneau mural d'atelier avec outils suspendus",
        "background": "étagères avec boîtes de vis à gauche, établi sombre en bas",
        "detected_objects": [
            {
                "label": "tournevis",
                "color": "manches rouges et jaunes",
                "position": "centre, alignés en rangée",
                "state": "suspendus",
                "bounding_box": None,
            },
            {
                "label": "pinces",
                "color": "rouge/orange",
                "position": "droite",
                "state": "suspendues",
                "bounding_box": None,
            },
            {
                "label": "perceuses",
                "color": "jaune et noir",
                "position": "premier plan, sur l'établi",
                "state": "posées",
                "bounding_box": None,
            },
            {
                "label": "réglette lumineuse LED",
                "color": "blanc/bleuté",
                "position": "centre, horizontale",
                "state": "allumée",
                "bounding_box": None,
            },
        ],
    },
    "workbench_2.jpg": {
        "main_subject": "un établi encombré d'outils divers",
        "background": "surface en bois et débris d'atelier (copeaux, chutes)",
        "detected_objects": [
            {
                "label": "perceuse-visseuse",
                "color": "noir avec détails orange",
                "position": "centre",
                "state": "posée",
                "bounding_box": None,
            },
            {
                "label": "mètre ruban",
                "color": "jaune et noir",
                "position": "centre bas",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "pied à coulisse",
                "color": "argenté/métal",
                "position": "centre, vertical",
                "state": None,
                "bounding_box": None,
            },
            {
                "label": "gobelet",
                "color": "turquoise",
                "position": "en haut à droite",
                "state": None,
                "bounding_box": None,
            },
        ],
    },
}
